---

- name: Setup Pop_OS
  hosts: localhost

  tasks:
    - name: Download terminator
      ansible.builtin.package: 
        name: terminator
        state: present
    
    - name: Remove gnome terminal
      ansible.builtin.package:
        name: gnome-terminal
        state: absent
    
    - name: Launch terminator to create default directories
      ansible.builtin.shell: terminator
    
    - name: wait 5 seconds
      ansible.builtin.pause:
        seconds: 5
    
    - name: kill terminator
      ansible.builtin.shell: kill terminator
      ignore_errors: yes
    
    - name: Import terminator profile
      ansible.builtin.template:
        src: terminator.j2
        dest: ~/.config/terminator
      
    - name: Download zsh
      ansible.builtin.package:
        name: zsh
        state: present
      become: true
    
    - name: Install Oh My Zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        depth: 1
     
    - name: Install zsh-autosuggestions plugin #
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1
     
    - name: Install zsh-completions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1
     
    - name: Install zsh-syntax-highlighting plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1
    
    - name: Download important applications
      ansible.builtin.package:
        name:
          - keepassxc
          - flameshot
          - git
          - network-manager-openvpn
        state: present
      become: true

    - name: Download flatpak applications
      ansible.builtin.flatpak:
        name:
          - com.todoist.Todoist
          - io.typora.Typora
          - org.chromium.Chromium
          - org.mozilla.Thunderbird
          - org.onlyoffice.desktopeditors
          - org.libreoffice.LibreOffice
          - typora
          - slack
    - name: Create directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/Documents/projects
        - ~/Documents/notes
        - ~/Documents/projects/work
        - ~/Documents/projects/personal
        - ~/Documents/projects/work/automation
        - ~/Documents/projects/work/sysAdmin
    
    - name: Install zed
      ansible.builtin.shell: curl -f https://zed.dev/install.sh | sh
